INSERT INTO vets (first_name, last_name) SELECT 'James', 'Carter' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=1);
INSERT INTO vets (first_name, last_name) SELECT 'Helen', 'Leary' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=2);
INSERT INTO vets (first_name, last_name) SELECT 'Linda', 'Douglas' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=3);
INSERT INTO vets (first_name, last_name) SELECT 'Rafael', 'Ortega' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=4);
INSERT INTO vets (first_name, last_name) SELECT 'Henry', 'Stevens' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=5);
INSERT INTO vets (first_name, last_name) SELECT 'Sharon', 'Jenkins' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=6);

INSERT INTO specialties (name) SELECT 'radiology' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='radiology');
INSERT INTO specialties (name) SELECT 'surgery' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='surgery'); 
INSERT INTO specialties (name) SELECT 'dentistry' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='dentistry');

INSERT INTO vet_specialties VALUES (2, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (3, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (3, 3) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (4, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (5, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;

INSERT INTO types (name) SELECT 'cat' WHERE NOT EXISTS (SELECT * FROM types WHERE name='cat');
INSERT INTO types (name) SELECT 'dog' WHERE NOT EXISTS (SELECT * FROM types WHERE name='dog');
INSERT INTO types (name) SELECT 'lizard' WHERE NOT EXISTS (SELECT * FROM types WHERE name='lizard');
INSERT INTO types (name) SELECT 'snake' WHERE NOT EXISTS (SELECT * FROM types WHERE name='snake');
INSERT INTO types (name) SELECT 'bird' WHERE NOT EXISTS (SELECT * FROM types WHERE name='bird');
INSERT INTO types (name) SELECT 'hamster' WHERE NOT EXISTS (SELECT * FROM types WHERE name='hamster');

INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=1);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=2);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=3);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=4);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=5);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=6);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=7);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=8);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=9);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=10);

INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Leo', '2000-09-07', 1, 1 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=1);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Basil', '2002-08-06', 6, 2 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=2);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Rosy', '2001-04-17', 2, 3 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=3);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Jewel', '2000-03-07', 2, 3 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=4);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Iggy', '2000-11-30', 3, 4 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=5);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'George', '2000-01-20', 4, 5 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=6);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Samantha', '1995-09-04', 1, 6 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=7);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Max', '1995-09-04', 1, 6 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=8);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucky', '1999-08-06', 5, 7 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=9);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Mulligan', '1997-02-24', 2, 8 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=10);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Freddy', '2000-03-09', 5, 9 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=11);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucky', '2000-06-24', 2, 10 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=12);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Sly', '2002-06-08', 1, 10 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=13);

INSERT INTO visits (pet_id, visit_date, description) SELECT 7, '2010-03-04', 'rabies shot' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=1);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2011-03-04', 'rabies shot' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=2);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2009-06-04', 'neutered' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=3);
INSERT INTO visits (pet_id, visit_date, description) SELECT 7, '2008-09-04', 'spayed' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=4);

-- Additional test data (appended; do not edit existing rows above)

-- Additional owners
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Michael', 'Jones', '100 Main St.', 'Madison', '6085551000' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=11);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jason', 'Johnson', '137 Oak Ave.', 'Sun Prairie', '6085551023' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=12);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Susan', 'Jones', '174 Maple Dr.', 'Verona', '6085551046' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=13);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Robert', 'Nelson', '211 Cedar Ln.', 'Fitchburg', '6085551069' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=14);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Michelle', 'Martin', '248 Pine Rd.', 'Stoughton', '6085551092' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=15);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Stephanie', 'Martin', '285 Elm St.', 'Middleton', '6085551115' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=16);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Margaret', 'King', '322 Walnut Blvd.', 'Waunakee', '6085551138' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=17);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Nicholas', 'Garcia', '359 Birch Way', 'McFarland', '6085551161' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=18);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Linda', 'Johnson', '396 Spruce Ct.', 'Monona', '6085551184' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=19);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Mary', 'Scott', '433 Willow Pl.', 'Windsor', '6085551207' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=20);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Patricia', 'Jackson', '470 Chestnut St.', 'DeForest', '6085551230' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=21);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Melissa', 'Young', '507 Hickory Ln.', 'Cottage Grove', '6085551253' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=22);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jacob', 'Harris', '544 Magnolia Ave.', 'Oregon', '6085551276' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=23);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Kenneth', 'Taylor', '581 Sycamore Dr.', 'Cross Plains', '6085551299' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=24);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Joshua', 'Garcia', '618 Poplar Rd.', 'Mount Horeb', '6085551322' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=25);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Barbara', 'Baker', '655 Dogwood St.', 'Madison', '6085551345' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=26);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Emily', 'Adams', '692 Aspen Way', 'Sun Prairie', '6085551368' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=27);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Mark', 'Thompson', '729 Beech Ct.', 'Verona', '6085551391' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=28);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Stephen', 'Miller', '766 Holly Ln.', 'Fitchburg', '6085551414' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=29);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Justin', 'White', '803 Juniper Pl.', 'Stoughton', '6085551437' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=30);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Kimberly', 'Thomas', '840 Main St.', 'Middleton', '6085551460' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=31);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Brian', 'Wright', '877 Oak Ave.', 'Waunakee', '6085551483' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=32);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Larry', 'Hill', '914 Maple Dr.', 'McFarland', '6085551506' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=33);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jessica', 'Allen', '951 Cedar Ln.', 'Monona', '6085551529' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=34);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Andrew', 'Anderson', '988 Pine Rd.', 'Windsor', '6085551552' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=35);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Ashley', 'Moore', '1025 Elm St.', 'DeForest', '6085551575' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=36);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Daniel', 'Carter', '1062 Walnut Blvd.', 'Cottage Grove', '6085551598' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=37);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Carol', 'Green', '1099 Birch Way', 'Oregon', '6085551621' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=38);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Donna', 'Smith', '1136 Spruce Ct.', 'Cross Plains', '6085551644' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=39);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jennifer', 'Smith', '1173 Willow Pl.', 'Mount Horeb', '6085551667' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=40);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Sarah', 'Mitchell', '1210 Chestnut St.', 'Madison', '6085551690' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=41);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Deborah', 'Walker', '1247 Hickory Ln.', 'Sun Prairie', '6085551713' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=42);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Ryan', 'Williams', '1284 Magnolia Ave.', 'Verona', '6085551736' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=43);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Amanda', 'Williams', '1321 Sycamore Dr.', 'Fitchburg', '6085551759' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=44);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Christopher', 'Brown', '1358 Poplar Rd.', 'Stoughton', '6085551782' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=45);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Kevin', 'Miller', '1395 Dogwood St.', 'Middleton', '6085551805' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=46);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Lisa', 'Wilson', '1432 Aspen Way', 'Waunakee', '6085551828' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=47);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Brandon', 'Taylor', '1469 Beech Ct.', 'McFarland', '6085551851' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=48);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Eric', 'Smith', '1506 Holly Ln.', 'Monona', '6085551874' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=49);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Nancy', 'Brown', '1543 Juniper Pl.', 'Windsor', '6085551897' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=50);

-- Additional pets
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Buddy', '2020-03-13', 1, 11 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=14);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Bella', '2025-01-03', 2, 11 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=15);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Charlie', '2023-02-12', 3, 12 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=16);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Luna', '2024-01-17', 4, 12 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=17);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Daisy', '2018-01-03', 5, 13 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=18);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Cooper', '2021-07-03', 6, 13 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=19);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Milo', '2018-02-18', 1, 14 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=20);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lily', '2021-01-27', 2, 14 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=21);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Rocky', '2024-02-08', 3, 15 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=22);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucy', '2025-11-19', 4, 15 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=23);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Bear', '2015-10-19', 5, 16 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=24);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Molly', '2021-01-08', 6, 16 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=25);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Duke', '2015-09-28', 1, 17 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=26);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Sadie', '2017-05-14', 2, 17 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=27);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Tucker', '2017-09-04', 3, 18 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=28);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Maggie', '2024-05-18', 4, 19 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=29);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Oliver', '2025-03-04', 5, 20 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=30);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Sophie', '2024-10-21', 6, 21 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=31);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Jack', '2018-06-04', 1, 22 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=32);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Chloe', '2023-12-03', 2, 23 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=33);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Toby', '2024-01-20', 3, 24 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=34);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Penny', '2018-08-22', 4, 25 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=35);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Bailey', '2023-07-25', 5, 26 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=36);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Zoe', '2020-08-19', 6, 27 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=37);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Oscar', '2022-06-10', 1, 28 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=38);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Ruby', '2018-03-23', 2, 29 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=39);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Finn', '2018-02-19', 3, 30 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=40);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Rosie', '2019-09-16', 4, 31 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=41);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Murphy', '2020-12-15', 5, 32 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=42);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Coco', '2019-10-03', 6, 33 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=43);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Henry', '2016-09-14', 1, 34 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=44);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Willow', '2017-06-05', 2, 35 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=45);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Leo', '2022-07-02', 3, 36 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=46);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Ginger', '2025-02-25', 4, 37 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=47);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Loki', '2023-10-26', 5, 38 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=48);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Hazel', '2020-06-23', 6, 39 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=49);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Buster', '2020-10-16', 1, 40 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=50);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Mochi', '2024-08-03', 2, 41 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=51);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Simba', '2016-05-16', 3, 42 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=52);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Pepper', '2025-02-02', 4, 43 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=53);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Biscuit', '2019-11-19', 5, 44 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=54);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Olive', '2025-08-10', 6, 45 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=55);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Shadow', '2021-11-12', 1, 46 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=56);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Nala', '2015-08-12', 2, 47 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=57);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Tank', '2017-10-04', 3, 48 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=58);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Roxy', '2022-01-07', 4, 49 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=59);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Bandit', '2019-03-24', 5, 50 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=60);

-- Additional visits
INSERT INTO visits (pet_id, visit_date, description) SELECT 4, '2022-02-25', 'annual checkup' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=5);
INSERT INTO visits (pet_id, visit_date, description) SELECT 28, '2022-02-27', 'vaccination' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=6);
INSERT INTO visits (pet_id, visit_date, description) SELECT 59, '2020-07-18', 'dental cleaning' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=7);
INSERT INTO visits (pet_id, visit_date, description) SELECT 37, '2022-06-28', 'limping' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=8);
INSERT INTO visits (pet_id, visit_date, description) SELECT 4, '2021-03-11', 'skin irritation' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=9);
INSERT INTO visits (pet_id, visit_date, description) SELECT 37, '2022-12-08', 'routine exam' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=10);
INSERT INTO visits (pet_id, visit_date, description) SELECT 12, '2020-07-25', 'emergency visit' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=11);
INSERT INTO visits (pet_id, visit_date, description) SELECT 6, '2024-07-03', 'follow-up' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=12);
INSERT INTO visits (pet_id, visit_date, description) SELECT 1, '2022-12-15', 'blood work' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=13);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2020-02-22', 'x-ray' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=14);
INSERT INTO visits (pet_id, visit_date, description) SELECT 11, '2021-01-10', 'ear infection' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=15);
INSERT INTO visits (pet_id, visit_date, description) SELECT 60, '2023-10-16', 'flea treatment' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=16);
INSERT INTO visits (pet_id, visit_date, description) SELECT 18, '2023-01-25', 'deworming' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=17);
INSERT INTO visits (pet_id, visit_date, description) SELECT 21, '2022-09-26', 'weight check' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=18);
INSERT INTO visits (pet_id, visit_date, description) SELECT 32, '2021-10-21', 'nail trim' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=19);
INSERT INTO visits (pet_id, visit_date, description) SELECT 35, '2024-06-01', 'annual checkup' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=20);
INSERT INTO visits (pet_id, visit_date, description) SELECT 27, '2025-09-14', 'vaccination' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=21);
INSERT INTO visits (pet_id, visit_date, description) SELECT 45, '2024-11-26', 'dental cleaning' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=22);
INSERT INTO visits (pet_id, visit_date, description) SELECT 44, '2024-08-17', 'limping' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=23);
INSERT INTO visits (pet_id, visit_date, description) SELECT 44, '2023-06-17', 'skin irritation' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=24);
INSERT INTO visits (pet_id, visit_date, description) SELECT 3, '2025-03-24', 'routine exam' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=25);
INSERT INTO visits (pet_id, visit_date, description) SELECT 54, '2020-08-22', 'emergency visit' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=26);
INSERT INTO visits (pet_id, visit_date, description) SELECT 18, '2021-06-11', 'follow-up' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=27);
INSERT INTO visits (pet_id, visit_date, description) SELECT 37, '2023-02-24', 'blood work' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=28);
INSERT INTO visits (pet_id, visit_date, description) SELECT 31, '2023-10-25', 'x-ray' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=29);
INSERT INTO visits (pet_id, visit_date, description) SELECT 23, '2020-04-19', 'ear infection' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=30);
INSERT INTO visits (pet_id, visit_date, description) SELECT 6, '2025-06-01', 'flea treatment' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=31);
INSERT INTO visits (pet_id, visit_date, description) SELECT 59, '2022-04-13', 'deworming' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=32);
INSERT INTO visits (pet_id, visit_date, description) SELECT 36, '2024-12-27', 'weight check' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=33);
INSERT INTO visits (pet_id, visit_date, description) SELECT 60, '2020-11-10', 'nail trim' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=34);
INSERT INTO visits (pet_id, visit_date, description) SELECT 33, '2025-12-08', 'annual checkup' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=35);
INSERT INTO visits (pet_id, visit_date, description) SELECT 36, '2023-03-05', 'vaccination' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=36);
INSERT INTO visits (pet_id, visit_date, description) SELECT 36, '2023-07-25', 'dental cleaning' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=37);
INSERT INTO visits (pet_id, visit_date, description) SELECT 31, '2020-01-05', 'limping' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=38);
INSERT INTO visits (pet_id, visit_date, description) SELECT 31, '2021-01-09', 'skin irritation' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=39);
INSERT INTO visits (pet_id, visit_date, description) SELECT 53, '2022-11-09', 'routine exam' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=40);
INSERT INTO visits (pet_id, visit_date, description) SELECT 29, '2025-07-01', 'emergency visit' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=41);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2024-02-17', 'follow-up' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=42);
INSERT INTO visits (pet_id, visit_date, description) SELECT 24, '2025-02-03', 'blood work' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=43);
INSERT INTO visits (pet_id, visit_date, description) SELECT 29, '2020-09-13', 'x-ray' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=44);
INSERT INTO visits (pet_id, visit_date, description) SELECT 5, '2024-12-21', 'ear infection' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=45);
INSERT INTO visits (pet_id, visit_date, description) SELECT 27, '2020-06-09', 'flea treatment' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=46);
INSERT INTO visits (pet_id, visit_date, description) SELECT 32, '2020-09-11', 'deworming' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=47);
INSERT INTO visits (pet_id, visit_date, description) SELECT 28, '2022-01-21', 'weight check' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=48);
INSERT INTO visits (pet_id, visit_date, description) SELECT 42, '2021-07-03', 'nail trim' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=49);
INSERT INTO visits (pet_id, visit_date, description) SELECT 47, '2025-03-12', 'annual checkup' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=50);
INSERT INTO visits (pet_id, visit_date, description) SELECT 44, '2021-12-03', 'vaccination' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=51);
INSERT INTO visits (pet_id, visit_date, description) SELECT 54, '2025-01-25', 'dental cleaning' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=52);
INSERT INTO visits (pet_id, visit_date, description) SELECT 35, '2023-09-10', 'limping' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=53);
INSERT INTO visits (pet_id, visit_date, description) SELECT 11, '2025-05-25', 'skin irritation' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=54);
INSERT INTO visits (pet_id, visit_date, description) SELECT 55, '2023-06-05', 'routine exam' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=55);
INSERT INTO visits (pet_id, visit_date, description) SELECT 36, '2022-09-04', 'emergency visit' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=56);
INSERT INTO visits (pet_id, visit_date, description) SELECT 42, '2021-10-13', 'follow-up' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=57);
INSERT INTO visits (pet_id, visit_date, description) SELECT 29, '2020-12-05', 'blood work' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=58);
INSERT INTO visits (pet_id, visit_date, description) SELECT 31, '2025-01-12', 'x-ray' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=59);
INSERT INTO visits (pet_id, visit_date, description) SELECT 30, '2025-12-24', 'ear infection' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=60);
INSERT INTO visits (pet_id, visit_date, description) SELECT 47, '2025-08-10', 'flea treatment' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=61);
INSERT INTO visits (pet_id, visit_date, description) SELECT 29, '2020-03-17', 'deworming' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=62);
INSERT INTO visits (pet_id, visit_date, description) SELECT 22, '2024-09-18', 'weight check' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=63);
INSERT INTO visits (pet_id, visit_date, description) SELECT 10, '2022-09-04', 'nail trim' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=64);
INSERT INTO visits (pet_id, visit_date, description) SELECT 36, '2025-06-08', 'annual checkup' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=65);
INSERT INTO visits (pet_id, visit_date, description) SELECT 59, '2024-06-03', 'vaccination' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=66);
INSERT INTO visits (pet_id, visit_date, description) SELECT 19, '2024-04-07', 'dental cleaning' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=67);
INSERT INTO visits (pet_id, visit_date, description) SELECT 58, '2022-05-13', 'limping' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=68);
INSERT INTO visits (pet_id, visit_date, description) SELECT 3, '2024-02-07', 'skin irritation' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=69);
INSERT INTO visits (pet_id, visit_date, description) SELECT 34, '2021-01-07', 'routine exam' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=70);
INSERT INTO visits (pet_id, visit_date, description) SELECT 19, '2024-04-03', 'emergency visit' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=71);
INSERT INTO visits (pet_id, visit_date, description) SELECT 40, '2022-02-11', 'follow-up' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=72);
INSERT INTO visits (pet_id, visit_date, description) SELECT 37, '2024-03-26', 'blood work' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=73);
INSERT INTO visits (pet_id, visit_date, description) SELECT 36, '2021-08-16', 'x-ray' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=74);
INSERT INTO visits (pet_id, visit_date, description) SELECT 48, '2023-01-09', 'ear infection' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=75);
INSERT INTO visits (pet_id, visit_date, description) SELECT 47, '2024-08-11', 'flea treatment' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=76);
INSERT INTO visits (pet_id, visit_date, description) SELECT 27, '2021-09-05', 'deworming' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=77);
INSERT INTO visits (pet_id, visit_date, description) SELECT 41, '2025-01-26', 'weight check' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=78);
INSERT INTO visits (pet_id, visit_date, description) SELECT 52, '2024-10-16', 'nail trim' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=79);
INSERT INTO visits (pet_id, visit_date, description) SELECT 23, '2025-10-04', 'annual checkup' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=80);

-- Additional vets
INSERT INTO vets (first_name, last_name) SELECT 'Olivia', 'Reed' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=7);
INSERT INTO vets (first_name, last_name) SELECT 'Noah', 'Bennett' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=8);
INSERT INTO vets (first_name, last_name) SELECT 'Emma', 'Russell' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=9);
INSERT INTO vets (first_name, last_name) SELECT 'Liam', 'Foster' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=10);
INSERT INTO vets (first_name, last_name) SELECT 'Ava', 'Hayes' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=11);
INSERT INTO vets (first_name, last_name) SELECT 'Ethan', 'Brooks' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=12);
INSERT INTO vets (first_name, last_name) SELECT 'Mia', 'Sanders' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=13);
INSERT INTO vets (first_name, last_name) SELECT 'Lucas', 'Parker' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=14);
INSERT INTO vets (first_name, last_name) SELECT 'Sophia', 'Morgan' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=15);

-- Additional vet_specialties
INSERT INTO vet_specialties VALUES (7, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (7, 3) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (8, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (9, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (9, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (9, 3) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (10, 3) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (11, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (12, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (12, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (13, 3) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (15, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
